{
 "title": "Juice Shop Instance Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "difficulties",
    "label": "Difficulty Levels supported by JuiceShop",
    "query": "1,2,3,4,5,6"
   }
  ]
 },
 "panels": [
  { "title": "Challenge Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "repeat": "difficulties",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved Challenges by Category",
   "type": "stat",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (category)(juiceshop_challenges_solved{}) / sum by (category)(juiceshop_challenges_total{}) * 100 != 0",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Cheat Score",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "juiceshop_cheat_score" }
   ]
  },
  {
   "title": "Business Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Social Interactions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "juiceshop_user_social_interactions{}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "User Signups",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(juiceshop_users_registered{}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Conversion Rate",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 9, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "juiceshop_orders_placed_total" }
     ]
    },
    {
     "title": "Digital Wallets Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 5, "x": 13, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "juiceshop_wallet_balance_total" }
     ]
    },
    {
     "title": "Customer Base",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "juiceshop_users_registered{type=\"standard\"}"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "juiceshop_users_registered{type=\"deluxe\"}"
      }
     ]
    }
   ]
  },
  { "title": "Technical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Requests per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_count{app=\"juiceshop\"}[1m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "File Uploads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(file_uploads_count[1h]) * 3600",
     "legendFormat": "{{file_type}}"
    }
   ]
  },
  {
   "title": "File Upload Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(file_upload_errors[1h]) * 3600",
     "legendFormat": "{{file_type}}"
    }
   ]
  },
  {
   "title": "Startup Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg by (task)(juiceshop_startup_duration_seconds))",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{}[2m]) * 100",
     "legendFormat": "User CPU"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{}[2m]) * 100",
     "legendFormat": "Sys CPU"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds{}" }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Juice Shop Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(juiceshop_version_info{}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 32 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_handles_total{}", "legendFormat": "Active Handler" },
    { "expr": "nodejs_active_requests_total{}", "legendFormat": "Active Request" }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "Process Memory"
    },
    { "expr": "nodejs_heap_size_total_bytes{}", "legendFormat": "Heap Total" },
    { "expr": "nodejs_heap_size_used_bytes{}", "legendFormat": "Heap Used" },
    { "expr": "nodejs_external_memory_bytes{}", "legendFormat": "External Memory" }
   ]
  }
 ]
}