name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #jobs required for the build
      - name: Build Jobs
        run: echo Build Jobs
        
  # Run security scans
  scan:
    needs: build
    name: scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript']
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  # Deploy the app
  deploy:
    name: Deploy
    needs: scan
    runs-on: ubuntu-latest

    steps:
    - run: echo "Deploying the app.."
